ALTER TABLE sync_folder_preserve_delete_resolutions ADD COLUMN request_version INTEGER NOT NULL DEFAULT 1 CHECK(request_version IN (1,2));
ALTER TABLE sync_folder_preserve_delete_resolutions ADD COLUMN known_cursor INTEGER CHECK(known_cursor IS NULL OR known_cursor>0);
ALTER TABLE sync_folder_preserve_delete_resolutions ADD COLUMN first_cursor INTEGER CHECK(first_cursor IS NULL OR first_cursor>0);
ALTER TABLE sync_folder_preserve_delete_resolutions ADD COLUMN last_cursor INTEGER CHECK(last_cursor IS NULL OR last_cursor>=first_cursor);
ALTER TABLE sync_folder_preserve_delete_resolutions ADD COLUMN clone_count INTEGER NOT NULL DEFAULT 0 CHECK(clone_count>=0);
UPDATE sync_folder_preserve_delete_resolutions SET first_cursor=recovered_cursor,last_cursor=deleted_cursor WHERE request_version=1;
CREATE TABLE sync_folder_preserve_delete_clones(
 user_id BLOB NOT NULL CHECK(typeof(user_id)='blob' AND length(user_id)=16),resolution_operation_id BLOB NOT NULL CHECK(typeof(resolution_operation_id)='blob' AND length(resolution_operation_id)=16),ordinal INTEGER NOT NULL CHECK(ordinal>=0),original_folder_id BLOB NOT NULL CHECK(typeof(original_folder_id)='blob' AND length(original_folder_id)=16),recovered_folder_id BLOB NOT NULL CHECK(typeof(recovered_folder_id)='blob' AND length(recovered_folder_id)=16),create_cursor INTEGER NOT NULL CHECK(create_cursor>0),delete_cursor INTEGER NOT NULL CHECK(delete_cursor>create_cursor),PRIMARY KEY(user_id,resolution_operation_id,ordinal),UNIQUE(user_id,resolution_operation_id,original_folder_id),UNIQUE(user_id,resolution_operation_id,recovered_folder_id),FOREIGN KEY(user_id,resolution_operation_id) REFERENCES sync_folder_preserve_delete_resolutions(user_id,resolution_operation_id),FOREIGN KEY(user_id,recovered_folder_id) REFERENCES sync_objects(user_id,object_id),FOREIGN KEY(user_id,create_cursor) REFERENCES sync_change_log(user_id,cursor),FOREIGN KEY(user_id,delete_cursor) REFERENCES sync_change_log(user_id,cursor));
CREATE TRIGGER sync_folder_preserve_delete_clone_insert_guard BEFORE INSERT ON sync_folder_preserve_delete_clones WHEN NOT EXISTS(SELECT 1 FROM sync_folder_preserve_delete_resolutions r JOIN sync_change_log create_log ON create_log.user_id=r.user_id AND create_log.cursor=NEW.create_cursor AND create_log.object_id=NEW.recovered_folder_id AND create_log.mutation='create' JOIN sync_object_versions create_v ON create_v.user_id=create_log.user_id AND create_v.object_id=create_log.object_id AND create_v.revision=1 AND create_v.operation_id=create_log.operation_id AND create_v.object_type='folder' AND create_v.parent_id=r.recovered_folder_id AND create_v.deleted=0 JOIN sync_change_log delete_log ON delete_log.user_id=r.user_id AND delete_log.cursor=NEW.delete_cursor AND delete_log.object_id=NEW.original_folder_id AND delete_log.mutation='delete' JOIN sync_object_versions delete_v ON delete_v.user_id=delete_log.user_id AND delete_v.object_id=delete_log.object_id AND delete_v.operation_id=delete_log.operation_id AND delete_v.object_type='folder' AND delete_v.deleted=1 WHERE r.user_id=NEW.user_id AND r.resolution_operation_id=NEW.resolution_operation_id AND r.request_version=2 AND r.status='completed' AND NEW.create_cursor=r.first_cursor+1+NEW.ordinal AND NEW.delete_cursor=r.first_cursor+1+(r.last_cursor-r.first_cursor-1)/2+NEW.ordinal AND r.last_cursor=r.first_cursor+2*r.clone_count+1 AND NEW.ordinal<r.clone_count) BEGIN SELECT RAISE(ABORT,'invalid folder preserve delete clone binding'); END;
CREATE TRIGGER sync_folder_preserve_delete_clone_no_update BEFORE UPDATE ON sync_folder_preserve_delete_clones BEGIN SELECT RAISE(ABORT,'folder preserve delete clone is immutable'); END;
CREATE TRIGGER sync_folder_preserve_delete_clone_no_delete BEFORE DELETE ON sync_folder_preserve_delete_clones WHEN EXISTS(SELECT 1 FROM users WHERE id=OLD.user_id) BEGIN SELECT RAISE(ABORT,'folder preserve delete clone is immutable'); END;
