DROP TRIGGER sync_inbox_linked_plan_state_guard;
CREATE TRIGGER sync_inbox_linked_plan_state_guard
BEFORE UPDATE OF status,completed_at_ms ON apply_plans
WHEN EXISTS(SELECT 1 FROM sync_inbox_apply_plans l WHERE l.plan_id=OLD.plan_id) AND NOT(
 (OLD.status='prepared' AND NEW.status='applying' AND NEW.completed_at_ms IS NULL AND EXISTS(SELECT 1 FROM sync_inbox_apply_plans l JOIN sync_inbox_changes i ON i.cursor=l.cursor JOIN apply_steps s ON s.plan_id=OLD.plan_id AND s.step_index=0 WHERE l.plan_id=OLD.plan_id AND i.state='applying' AND s.state='pending'))
 OR (OLD.status='prepared' AND NEW.status='failed' AND NEW.completed_at_ms IS NOT NULL AND EXISTS(SELECT 1 FROM sync_inbox_apply_plans l JOIN sync_inbox_changes i ON i.cursor=l.cursor JOIN apply_steps s ON s.plan_id=OLD.plan_id AND s.step_index=0 WHERE l.plan_id=OLD.plan_id AND i.state='pending' AND s.state='pending' AND NOT EXISTS(SELECT 1 FROM apply_folder_publications f WHERE f.plan_id=OLD.plan_id) AND NOT EXISTS(SELECT 1 FROM apply_folder_mutations m WHERE m.plan_id=OLD.plan_id)))
 OR (OLD.status='failed' AND NEW.status='prepared' AND NEW.completed_at_ms IS NULL AND EXISTS(SELECT 1 FROM sync_inbox_apply_plans l JOIN sync_inbox_changes i ON i.cursor=l.cursor JOIN apply_steps s ON s.plan_id=OLD.plan_id AND s.step_index=0 WHERE l.plan_id=OLD.plan_id AND i.state='pending' AND s.state='pending' AND NOT EXISTS(SELECT 1 FROM apply_folder_publications f WHERE f.plan_id=OLD.plan_id) AND NOT EXISTS(SELECT 1 FROM apply_folder_mutations m WHERE m.plan_id=OLD.plan_id) AND EXISTS(SELECT 1 FROM sync_baselines b WHERE b.object_id=i.object_id AND b.revision=i.revision-1) AND NOT EXISTS(SELECT 1 FROM sync_inbox_changes earlier WHERE earlier.object_id=i.object_id AND earlier.cursor<i.cursor AND earlier.state<>'applied') AND NOT EXISTS(SELECT 1 FROM apply_plans active WHERE active.plan_id<>OLD.plan_id AND active.status IN ('prepared','applying'))))
 OR (OLD.status='applying' AND NEW.status='completed' AND NEW.completed_at_ms IS NOT NULL AND EXISTS(SELECT 1 FROM sync_inbox_apply_plans l JOIN sync_inbox_changes i ON i.cursor=l.cursor JOIN apply_steps s ON s.plan_id=OLD.plan_id AND s.step_index=0 WHERE l.plan_id=OLD.plan_id AND i.state='applied' AND s.state='applied' AND EXISTS(SELECT 1 FROM sync_baselines baseline WHERE baseline.object_id=i.object_id AND baseline.revision=i.revision AND baseline.operation_id=i.operation_id)))
)
BEGIN SELECT RAISE(ABORT, 'linked inbox apply plan state transition is inconsistent'); END;
