CREATE TABLE conflict_folder_divergent_move_recoveries(
 operation_id TEXT PRIMARY KEY,folder_id TEXT NOT NULL,recovered_folder_id TEXT NOT NULL UNIQUE,new_operation_id TEXT NOT NULL UNIQUE,
 attempted_relative TEXT NOT NULL,canonical_relative TEXT NOT NULL,recovery_relative TEXT NOT NULL UNIQUE,
 source_device INTEGER NOT NULL CHECK(source_device>0),source_inode INTEGER NOT NULL CHECK(source_inode>0),canonical_revision INTEGER NOT NULL CHECK(canonical_revision>0),canonical_nonce BLOB NOT NULL CHECK(typeof(canonical_nonce)='blob' AND length(canonical_nonce)=32),canonical_device INTEGER CHECK(canonical_device>0),canonical_inode INTEGER CHECK(canonical_inode>0),
 state TEXT NOT NULL CHECK(state IN ('prepared','evacuated','canonical_prepared','canonical_published','completed')),
 CHECK((state IN ('prepared','evacuated') AND canonical_device IS NULL AND canonical_inode IS NULL) OR (state IN ('canonical_prepared','canonical_published','completed') AND canonical_device IS NOT NULL AND canonical_inode IS NOT NULL)),
 FOREIGN KEY(operation_id) REFERENCES sync_outbox(operation_id) ON DELETE CASCADE) WITHOUT ROWID;
CREATE TRIGGER conflict_folder_divergent_move_insert_guard BEFORE INSERT ON conflict_folder_divergent_move_recoveries WHEN NEW.state<>'prepared' OR NEW.canonical_device IS NOT NULL OR NEW.canonical_inode IS NOT NULL OR NOT EXISTS(
 SELECT 1 FROM sync_outbox o JOIN sync_conflict_states c ON c.operation_id=o.operation_id JOIN sync_outbox_folder_intents i ON i.operation_id=o.operation_id
 WHERE o.operation_id=NEW.operation_id AND o.object_id=NEW.folder_id AND o.object_type='folder' AND o.mutation='move' AND o.status='conflict' AND o.conflict_code='base_revision_mismatch' AND o.parent_id IS NULL
 AND c.object_type='folder' AND c.deleted=0 AND c.parent_id IS NULL AND c.name<>o.name AND c.name=NEW.canonical_relative AND c.revision=NEW.canonical_revision AND c.revision>o.base_revision AND c.blob_hash IS NULL
 AND i.folder_id=o.object_id AND i.mutation_kind='move' AND i.device=NEW.source_device AND i.inode=NEW.source_inode AND NEW.attempted_relative=o.name
 AND NEW.recovered_folder_id<>NEW.folder_id AND NEW.new_operation_id<>NEW.operation_id AND NEW.canonical_relative<>NEW.attempted_relative
 AND substr(NEW.recovery_relative,1,length('_Konflikte/Wiederhergestellt/'))='_Konflikte/Wiederhergestellt/' AND instr(substr(NEW.recovery_relative,length('_Konflikte/Wiederhergestellt/')+1),'/')=0
 AND NOT EXISTS(SELECT 1 FROM sync_outbox later WHERE later.object_id=o.object_id AND later.sequence>o.sequence AND later.status IN ('pending','attempted','replay_mismatch','conflict'))
 AND NOT EXISTS(SELECT 1 FROM sync_outbox_dependencies d JOIN sync_outbox dependent ON dependent.operation_id=d.operation_id WHERE d.dependency_operation_id=o.operation_id AND dependent.status IN ('pending','attempted','replay_mismatch','conflict')))
BEGIN SELECT RAISE(ABORT,'invalid divergent folder move recovery'); END;
CREATE TRIGGER conflict_folder_divergent_move_identity_immutable BEFORE UPDATE OF operation_id,folder_id,recovered_folder_id,new_operation_id,attempted_relative,canonical_relative,recovery_relative,source_device,source_inode,canonical_revision,canonical_nonce ON conflict_folder_divergent_move_recoveries BEGIN SELECT RAISE(ABORT,'divergent folder move recovery identity is immutable'); END;
CREATE TRIGGER conflict_folder_divergent_move_state_guard BEFORE UPDATE OF state,canonical_device,canonical_inode ON conflict_folder_divergent_move_recoveries WHEN NOT(
 (OLD.state='prepared' AND NEW.state='evacuated' AND NEW.canonical_device IS NULL AND NEW.canonical_inode IS NULL AND NOT EXISTS(SELECT 1 FROM sync_outbox later JOIN sync_outbox original ON original.operation_id=OLD.operation_id WHERE later.object_id=OLD.folder_id AND later.sequence>original.sequence AND later.status IN ('pending','attempted','replay_mismatch','conflict')) AND NOT EXISTS(SELECT 1 FROM sync_outbox_dependencies d JOIN sync_outbox dependent ON dependent.operation_id=d.operation_id WHERE d.dependency_operation_id=OLD.operation_id AND dependent.status IN ('pending','attempted','replay_mismatch','conflict'))) OR
 (OLD.state='evacuated' AND NEW.state='canonical_prepared' AND NEW.canonical_device>0 AND NEW.canonical_inode>0) OR
 (OLD.state='canonical_prepared' AND NEW.state='canonical_published' AND NEW.canonical_device=OLD.canonical_device AND NEW.canonical_inode=OLD.canonical_inode) OR
 (OLD.state='canonical_published' AND NEW.state='completed' AND NEW.canonical_device=OLD.canonical_device AND NEW.canonical_inode=OLD.canonical_inode))
BEGIN SELECT RAISE(ABORT,'invalid divergent folder move recovery transition'); END;
CREATE TRIGGER conflict_folder_divergent_move_no_delete BEFORE DELETE ON conflict_folder_divergent_move_recoveries BEGIN SELECT RAISE(ABORT,'divergent folder move recovery is immutable'); END;

DROP VIEW sync_unresolved_local_intents;
CREATE VIEW sync_unresolved_local_intents AS SELECT DISTINCT o.object_id FROM sync_outbox o WHERE
 (o.status IN ('pending','attempted','replay_mismatch') AND NOT EXISTS(SELECT 1 FROM conflict_folder_create_note_members n JOIN conflict_folder_create_recoveries f ON f.operation_id=n.operation_id WHERE n.old_operation_id=o.operation_id AND f.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_move_delete_note_members n JOIN conflict_folder_move_delete_recoveries d ON d.operation_id=n.operation_id WHERE n.old_operation_id=o.operation_id AND d.state IN ('moved','completed')))
 OR (o.status='conflict' AND NOT EXISTS(SELECT 1 FROM sync_conflict_resolutions r WHERE r.operation_id=o.operation_id) AND NOT EXISTS(SELECT 1 FROM conflict_materializations m WHERE m.operation_id=o.operation_id AND m.state IN ('copy_staged','copy_published','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_create_recoveries f WHERE f.operation_id=o.operation_id AND f.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_move_delete_recoveries d WHERE d.operation_id=o.operation_id AND d.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_recoveries d WHERE d.operation_id=o.operation_id AND d.state IN ('evacuated','canonical_published','completed')));
