CREATE TABLE conflict_folder_divergent_move_note_members(
 operation_id TEXT NOT NULL,note_id TEXT NOT NULL UNIQUE,old_operation_id TEXT NOT NULL UNIQUE,new_operation_id TEXT NOT NULL UNIQUE,name TEXT NOT NULL,blob_hash BLOB NOT NULL CHECK(typeof(blob_hash)='blob' AND length(blob_hash)=32),create_blob_hash BLOB NOT NULL CHECK(typeof(create_blob_hash)='blob' AND length(create_blob_hash)=32),PRIMARY KEY(operation_id,note_id),FOREIGN KEY(operation_id) REFERENCES conflict_folder_divergent_move_recoveries(operation_id),FOREIGN KEY(old_operation_id) REFERENCES sync_outbox(operation_id)) WITHOUT ROWID;
CREATE TABLE conflict_folder_divergent_move_note_chains(
 operation_id TEXT NOT NULL,note_id TEXT NOT NULL,ordinal INTEGER NOT NULL CHECK(ordinal>0),old_operation_id TEXT NOT NULL UNIQUE,previous_operation_id TEXT NOT NULL,blob_hash BLOB NOT NULL CHECK(typeof(blob_hash)='blob' AND length(blob_hash)=32),PRIMARY KEY(operation_id,note_id,ordinal),FOREIGN KEY(operation_id,note_id) REFERENCES conflict_folder_divergent_move_note_members(operation_id,note_id),FOREIGN KEY(old_operation_id) REFERENCES sync_outbox(operation_id)) WITHOUT ROWID;
CREATE TRIGGER conflict_folder_divergent_move_note_members_no_update BEFORE UPDATE ON conflict_folder_divergent_move_note_members BEGIN SELECT RAISE(ABORT,'divergent folder move note manifest immutable'); END;
CREATE TRIGGER conflict_folder_divergent_move_note_members_no_delete BEFORE DELETE ON conflict_folder_divergent_move_note_members BEGIN SELECT RAISE(ABORT,'divergent folder move note manifest immutable'); END;
CREATE TRIGGER conflict_folder_divergent_move_note_chains_no_update BEFORE UPDATE ON conflict_folder_divergent_move_note_chains BEGIN SELECT RAISE(ABORT,'divergent folder move note chain immutable'); END;
CREATE TRIGGER conflict_folder_divergent_move_note_chains_no_delete BEFORE DELETE ON conflict_folder_divergent_move_note_chains BEGIN SELECT RAISE(ABORT,'divergent folder move note chain immutable'); END;
CREATE TRIGGER conflict_folder_divergent_move_note_members_guard BEFORE INSERT ON conflict_folder_divergent_move_note_members WHEN NOT EXISTS(
 SELECT 1 FROM conflict_folder_divergent_move_recoveries r JOIN sync_outbox root ON root.operation_id=r.operation_id JOIN sync_outbox note ON note.operation_id=NEW.old_operation_id JOIN sync_outbox_dependencies d ON d.operation_id=note.operation_id WHERE r.operation_id=NEW.operation_id AND r.state='prepared' AND root.object_id=r.folder_id AND note.object_id=NEW.note_id AND note.status='pending' AND note.mutation='create' AND note.object_type='note' AND note.parent_id=r.folder_id AND note.name=NEW.name AND note.blob_hash=NEW.create_blob_hash AND d.dependency_operation_id=root.operation_id AND NOT EXISTS(SELECT 1 FROM sync_baselines b WHERE b.object_id=NEW.note_id) AND NOT EXISTS(SELECT 1 FROM sync_outbox_dependencies extra WHERE extra.operation_id=note.operation_id AND extra.dependency_operation_id<>root.operation_id)) BEGIN SELECT RAISE(ABORT,'invalid divergent folder move note member'); END;
CREATE TRIGGER conflict_folder_divergent_move_note_chains_guard BEFORE INSERT ON conflict_folder_divergent_move_note_chains WHEN NOT EXISTS(
 SELECT 1 FROM conflict_folder_divergent_move_note_members n JOIN sync_outbox u ON u.operation_id=NEW.old_operation_id WHERE n.operation_id=NEW.operation_id AND n.note_id=NEW.note_id AND u.object_id=n.note_id AND u.mutation='update' AND u.object_type='note' AND u.status='pending' AND u.blob_hash=NEW.blob_hash AND EXISTS(SELECT 1 FROM sync_outbox_dependencies d WHERE d.operation_id=u.operation_id AND d.dependency_operation_id=NEW.previous_operation_id) AND NOT EXISTS(SELECT 1 FROM sync_outbox_dependencies x WHERE x.operation_id=u.operation_id AND x.dependency_operation_id<>NEW.previous_operation_id) AND ((NEW.ordinal=1 AND NEW.previous_operation_id=n.old_operation_id) OR (NEW.ordinal>1 AND EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_chains p WHERE p.operation_id=NEW.operation_id AND p.note_id=NEW.note_id AND p.ordinal=NEW.ordinal-1 AND p.old_operation_id=NEW.previous_operation_id)))) BEGIN SELECT RAISE(ABORT,'invalid divergent folder move note chain'); END;
DROP TRIGGER conflict_folder_divergent_move_insert_guard;
CREATE TRIGGER conflict_folder_divergent_move_insert_guard BEFORE INSERT ON conflict_folder_divergent_move_recoveries WHEN NEW.state<>'prepared' OR NEW.canonical_device IS NOT NULL OR NEW.canonical_inode IS NOT NULL OR NOT EXISTS(
 SELECT 1 FROM sync_outbox o JOIN sync_conflict_states c ON c.operation_id=o.operation_id JOIN sync_outbox_folder_intents i ON i.operation_id=o.operation_id WHERE o.operation_id=NEW.operation_id AND o.object_id=NEW.folder_id AND o.object_type='folder' AND o.mutation='move' AND o.status='conflict' AND o.conflict_code='base_revision_mismatch' AND o.parent_id IS NULL AND c.object_type='folder' AND c.deleted=0 AND c.parent_id IS NULL AND c.name<>o.name AND c.name=NEW.canonical_relative AND c.revision=NEW.canonical_revision AND c.revision>o.base_revision AND c.blob_hash IS NULL AND i.folder_id=o.object_id AND i.mutation_kind='move' AND i.device=NEW.source_device AND i.inode=NEW.source_inode AND NEW.attempted_relative=o.name AND NEW.recovered_folder_id<>NEW.folder_id AND NEW.new_operation_id<>NEW.operation_id AND NEW.canonical_relative<>NEW.attempted_relative AND substr(NEW.recovery_relative,1,length('_Konflikte/Wiederhergestellt/'))='_Konflikte/Wiederhergestellt/' AND instr(substr(NEW.recovery_relative,length('_Konflikte/Wiederhergestellt/')+1),'/')=0 AND NOT EXISTS(SELECT 1 FROM sync_outbox later WHERE later.object_id=o.object_id AND later.sequence>o.sequence AND later.status IN ('pending','attempted','replay_mismatch','conflict'))) BEGIN SELECT RAISE(ABORT,'invalid divergent folder move recovery'); END;
CREATE VIEW IF NOT EXISTS conflict_folder_divergent_move_valid_note_topology AS
SELECT r.operation_id FROM conflict_folder_divergent_move_recoveries r WHERE NOT EXISTS(
 SELECT 1 FROM conflict_folder_divergent_move_note_members n WHERE n.operation_id=r.operation_id AND (
  EXISTS(SELECT 1 FROM sync_baselines b WHERE b.object_id=n.note_id)
  OR NOT EXISTS(SELECT 1 FROM sync_outbox c WHERE c.operation_id=n.old_operation_id AND c.object_id=n.note_id AND c.mutation='create' AND c.object_type='note' AND c.parent_id=r.folder_id AND c.name=n.name AND c.blob_hash=n.create_blob_hash AND c.status='pending')
  OR (SELECT COUNT(*) FROM sync_outbox o WHERE o.object_id=n.note_id)<>1+(SELECT COUNT(*) FROM conflict_folder_divergent_move_note_chains x WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id)
  OR (SELECT COUNT(*) FROM conflict_folder_divergent_move_note_chains x WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id)<>COALESCE((SELECT MAX(x.ordinal) FROM conflict_folder_divergent_move_note_chains x WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id),0)
  OR n.blob_hash<>COALESCE((SELECT x.blob_hash FROM conflict_folder_divergent_move_note_chains x WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id ORDER BY x.ordinal DESC LIMIT 1),n.create_blob_hash)
  OR EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_chains x WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id AND (NOT EXISTS(SELECT 1 FROM sync_outbox u WHERE u.operation_id=x.old_operation_id AND u.object_id=n.note_id AND u.mutation='update' AND u.object_type='note' AND u.status='pending' AND u.blob_hash=x.blob_hash) OR (SELECT COUNT(*) FROM sync_outbox_dependencies d WHERE d.operation_id=x.old_operation_id)<>1 OR NOT EXISTS(SELECT 1 FROM sync_outbox_dependencies d WHERE d.operation_id=x.old_operation_id AND d.dependency_operation_id=x.previous_operation_id) OR (x.ordinal=1 AND x.previous_operation_id<>n.old_operation_id) OR (x.ordinal>1 AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_chains p WHERE p.operation_id=x.operation_id AND p.note_id=x.note_id AND p.ordinal=x.ordinal-1 AND p.old_operation_id=x.previous_operation_id))))
  OR (SELECT COUNT(*) FROM sync_outbox_dependencies d WHERE d.dependency_operation_id=n.old_operation_id OR d.dependency_operation_id IN (SELECT x.old_operation_id FROM conflict_folder_divergent_move_note_chains x WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id))<>(SELECT COUNT(*) FROM conflict_folder_divergent_move_note_chains x WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id)
 ));

CREATE VIEW IF NOT EXISTS conflict_folder_divergent_move_replacements_complete AS
SELECT r.operation_id FROM conflict_folder_divergent_move_recoveries r WHERE
 EXISTS(SELECT 1 FROM sync_outbox f WHERE f.operation_id=r.new_operation_id AND f.object_id=r.recovered_folder_id AND f.mutation='create' AND f.object_type='folder' AND f.parent_id='7a3e2b0e-6a3d-4c5f-8a61-9a0c8d47f002' AND f.name=substr(r.recovery_relative,length('_Konflikte/Wiederhergestellt/')+1) AND f.status IN ('pending','attempted','accepted'))
 AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_members n WHERE n.operation_id=r.operation_id AND (
  NOT EXISTS(SELECT 1 FROM sync_outbox old WHERE old.operation_id=n.old_operation_id AND old.status='superseded')
  OR EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_chains x JOIN sync_outbox old ON old.operation_id=x.old_operation_id WHERE x.operation_id=n.operation_id AND x.note_id=n.note_id AND old.status<>'superseded')
  OR NOT EXISTS(SELECT 1 FROM sync_outbox replacement WHERE replacement.operation_id=n.new_operation_id AND replacement.object_id=n.note_id AND replacement.mutation='create' AND replacement.object_type='note' AND replacement.parent_id=r.recovered_folder_id AND replacement.name=n.name AND replacement.blob_hash=n.blob_hash AND replacement.status IN ('pending','attempted','accepted') AND (SELECT COUNT(*) FROM sync_outbox_dependencies d WHERE d.operation_id=replacement.operation_id)=1 AND EXISTS(SELECT 1 FROM sync_outbox_dependencies d WHERE d.operation_id=replacement.operation_id AND d.dependency_operation_id=r.new_operation_id))));

DROP TRIGGER conflict_folder_divergent_move_state_guard;
CREATE TRIGGER conflict_folder_divergent_move_state_guard BEFORE UPDATE OF state,canonical_device,canonical_inode ON conflict_folder_divergent_move_recoveries WHEN NOT(
 (OLD.state='prepared' AND NEW.state='evacuated' AND NEW.canonical_device IS NULL AND NEW.canonical_inode IS NULL AND EXISTS(SELECT 1 FROM conflict_folder_divergent_move_valid_note_topology valid WHERE valid.operation_id=OLD.operation_id) AND (SELECT COUNT(*) FROM sync_outbox_dependencies d JOIN sync_outbox dependent ON dependent.operation_id=d.operation_id WHERE d.dependency_operation_id=OLD.operation_id AND dependent.status IN ('pending','attempted','replay_mismatch','conflict'))=(SELECT COUNT(*) FROM conflict_folder_divergent_move_note_members n WHERE n.operation_id=OLD.operation_id) AND NOT EXISTS(SELECT 1 FROM sync_outbox_dependencies d JOIN sync_outbox dependent ON dependent.operation_id=d.operation_id WHERE d.dependency_operation_id=OLD.operation_id AND dependent.status IN ('pending','attempted','replay_mismatch','conflict') AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_members n WHERE n.operation_id=OLD.operation_id AND n.old_operation_id=dependent.operation_id)) AND NOT EXISTS(SELECT 1 FROM sync_outbox later JOIN sync_outbox original ON original.operation_id=OLD.operation_id WHERE later.object_id=OLD.folder_id AND later.sequence>original.sequence AND later.status IN ('pending','attempted','replay_mismatch','conflict'))) OR
 (OLD.state='evacuated' AND NEW.state='canonical_prepared' AND NEW.canonical_device>0 AND NEW.canonical_inode>0) OR (OLD.state='canonical_prepared' AND NEW.state='canonical_published' AND NEW.canonical_device=OLD.canonical_device AND NEW.canonical_inode=OLD.canonical_inode) OR (OLD.state='canonical_published' AND NEW.state='completed' AND NEW.canonical_device=OLD.canonical_device AND NEW.canonical_inode=OLD.canonical_inode AND EXISTS(SELECT 1 FROM conflict_folder_divergent_move_replacements_complete complete WHERE complete.operation_id=OLD.operation_id))) BEGIN SELECT RAISE(ABORT,'invalid divergent folder move recovery transition'); END;
DROP VIEW sync_unresolved_local_intents;
CREATE VIEW sync_unresolved_local_intents AS SELECT DISTINCT o.object_id FROM sync_outbox o WHERE
 (o.status IN ('pending','attempted','replay_mismatch') AND NOT EXISTS(SELECT 1 FROM conflict_folder_create_note_members n JOIN conflict_folder_create_recoveries f ON f.operation_id=n.operation_id WHERE n.old_operation_id=o.operation_id AND f.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_move_delete_note_members n JOIN conflict_folder_move_delete_recoveries d ON d.operation_id=n.operation_id WHERE n.old_operation_id=o.operation_id AND d.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_members n JOIN conflict_folder_divergent_move_recoveries d ON d.operation_id=n.operation_id WHERE (n.old_operation_id=o.operation_id OR EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_chains c WHERE c.operation_id=n.operation_id AND c.note_id=n.note_id AND c.old_operation_id=o.operation_id)) AND d.state IN ('evacuated','canonical_published','completed')))
 OR (o.status='conflict' AND NOT EXISTS(SELECT 1 FROM sync_conflict_resolutions r WHERE r.operation_id=o.operation_id) AND NOT EXISTS(SELECT 1 FROM conflict_materializations m WHERE m.operation_id=o.operation_id AND m.state IN ('copy_staged','copy_published','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_create_recoveries f WHERE f.operation_id=o.operation_id AND f.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_move_delete_recoveries d WHERE d.operation_id=o.operation_id AND d.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_recoveries d WHERE d.operation_id=o.operation_id AND d.state IN ('evacuated','canonical_published','completed')));
