DROP TRIGGER sync_folder_preserve_delete_resolution_insert_guard;
DROP TRIGGER sync_folder_preserve_delete_resolution_immutable;
DROP TRIGGER sync_folder_preserve_delete_resolution_state_guard;
DROP TRIGGER sync_folder_preserve_delete_resolution_no_delete;
ALTER TABLE sync_folder_preserve_delete_resolutions RENAME TO sync_folder_preserve_delete_resolutions_v1;
CREATE TABLE sync_folder_preserve_delete_resolutions(conflict_operation_id TEXT PRIMARY KEY,resolution_operation_id TEXT NOT NULL UNIQUE,folder_id TEXT NOT NULL,expected_revision INTEGER NOT NULL CHECK(expected_revision>0),recovered_folder_id TEXT,recovered_cursor INTEGER,deleted_cursor INTEGER,state TEXT NOT NULL CHECK(state IN ('prepared','resolved')),request_version INTEGER NOT NULL CHECK(request_version IN (1,2)),known_cursor INTEGER CHECK(known_cursor IS NULL OR known_cursor>=0),first_cursor INTEGER,last_cursor INTEGER,clone_count INTEGER NOT NULL DEFAULT 0 CHECK(clone_count>=0),CHECK((state='prepared' AND recovered_folder_id IS NULL AND recovered_cursor IS NULL AND deleted_cursor IS NULL AND first_cursor IS NULL AND last_cursor IS NULL) OR (state='resolved' AND recovered_folder_id IS NOT NULL AND recovered_cursor=first_cursor AND deleted_cursor=last_cursor AND first_cursor>0 AND last_cursor>=first_cursor)),FOREIGN KEY(conflict_operation_id) REFERENCES sync_outbox(operation_id));
INSERT INTO sync_folder_preserve_delete_resolutions(conflict_operation_id,resolution_operation_id,folder_id,expected_revision,recovered_folder_id,recovered_cursor,deleted_cursor,state,request_version,known_cursor,first_cursor,last_cursor,clone_count) SELECT conflict_operation_id,resolution_operation_id,folder_id,expected_revision,recovered_folder_id,recovered_cursor,deleted_cursor,state,1,NULL,recovered_cursor,deleted_cursor,0 FROM sync_folder_preserve_delete_resolutions_v1;
DROP TABLE sync_folder_preserve_delete_resolutions_v1;
CREATE TRIGGER sync_folder_preserve_delete_resolution_insert_guard BEFORE INSERT ON sync_folder_preserve_delete_resolutions WHEN NEW.state<>'prepared' OR NEW.request_version NOT IN (1,2) OR (NEW.request_version=1 AND COALESCE(NEW.known_cursor,0)<>0) OR (NEW.request_version=2 AND COALESCE(NEW.known_cursor,0)=0) OR NOT EXISTS(SELECT 1 FROM sync_outbox o JOIN sync_conflict_states c ON c.operation_id=o.operation_id WHERE o.operation_id=NEW.conflict_operation_id AND o.object_id=NEW.folder_id AND o.object_type='folder' AND o.mutation='delete' AND o.status='conflict' AND o.conflict_code='base_revision_mismatch' AND c.object_type='folder' AND c.deleted=0 AND c.revision=NEW.expected_revision) BEGIN SELECT RAISE(ABORT,'invalid folder preserve delete resolution'); END;
CREATE TRIGGER sync_folder_preserve_delete_resolution_immutable BEFORE UPDATE OF conflict_operation_id,resolution_operation_id,folder_id,expected_revision,request_version,known_cursor ON sync_folder_preserve_delete_resolutions BEGIN SELECT RAISE(ABORT,'folder preserve delete resolution identity immutable'); END;
CREATE TRIGGER sync_folder_preserve_delete_resolution_state_guard BEFORE UPDATE OF state,recovered_folder_id,recovered_cursor,deleted_cursor,first_cursor,last_cursor ON sync_folder_preserve_delete_resolutions WHEN NOT(OLD.state='prepared' AND NEW.state='resolved' AND NEW.recovered_folder_id IS NOT NULL AND NEW.recovered_cursor=NEW.first_cursor AND NEW.deleted_cursor=NEW.last_cursor AND NEW.first_cursor>0 AND NEW.last_cursor>=NEW.first_cursor) BEGIN SELECT RAISE(ABORT,'invalid folder preserve delete resolution transition'); END;
CREATE TRIGGER sync_folder_preserve_delete_resolution_no_delete BEFORE DELETE ON sync_folder_preserve_delete_resolutions BEGIN SELECT RAISE(ABORT,'folder preserve delete resolution durable'); END;
CREATE TABLE sync_folder_preserve_delete_clones(conflict_operation_id TEXT NOT NULL,ordinal INTEGER NOT NULL CHECK(ordinal>=0),original_folder_id TEXT NOT NULL,recovered_folder_id TEXT NOT NULL,create_cursor INTEGER NOT NULL CHECK(create_cursor>0),delete_cursor INTEGER NOT NULL CHECK(delete_cursor>create_cursor),PRIMARY KEY(conflict_operation_id,ordinal),UNIQUE(conflict_operation_id,original_folder_id),UNIQUE(conflict_operation_id,recovered_folder_id),FOREIGN KEY(conflict_operation_id) REFERENCES sync_folder_preserve_delete_resolutions(conflict_operation_id));
CREATE TRIGGER sync_folder_preserve_delete_clone_insert_guard BEFORE INSERT ON sync_folder_preserve_delete_clones WHEN NOT EXISTS(SELECT 1 FROM sync_folder_preserve_delete_resolutions p WHERE p.conflict_operation_id=NEW.conflict_operation_id AND p.state='resolved' AND p.request_version=2 AND p.last_cursor=p.first_cursor+2*p.clone_count+1 AND NEW.ordinal<p.clone_count AND NEW.create_cursor=p.first_cursor+1+NEW.ordinal AND NEW.delete_cursor=p.first_cursor+1+(p.last_cursor-p.first_cursor-1)/2+NEW.ordinal) BEGIN SELECT RAISE(ABORT,'invalid folder preserve delete clone'); END;
CREATE TRIGGER sync_folder_preserve_delete_clone_no_update BEFORE UPDATE ON sync_folder_preserve_delete_clones BEGIN SELECT RAISE(ABORT,'folder preserve delete clone immutable'); END;
CREATE TRIGGER sync_folder_preserve_delete_clone_no_delete BEFORE DELETE ON sync_folder_preserve_delete_clones BEGIN SELECT RAISE(ABORT,'folder preserve delete clone durable'); END;
DROP VIEW sync_unresolved_local_intents;
CREATE VIEW sync_unresolved_local_intents AS SELECT DISTINCT o.object_id FROM sync_outbox o WHERE
 (o.status IN ('pending','attempted','replay_mismatch') AND NOT EXISTS(SELECT 1 FROM conflict_folder_create_note_members n JOIN conflict_folder_create_recoveries f ON f.operation_id=n.operation_id WHERE n.old_operation_id=o.operation_id AND f.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_move_delete_note_members n JOIN conflict_folder_move_delete_recoveries d ON d.operation_id=n.operation_id WHERE n.old_operation_id=o.operation_id AND d.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_members n JOIN conflict_folder_divergent_move_recoveries d ON d.operation_id=n.operation_id WHERE (n.old_operation_id=o.operation_id OR EXISTS(SELECT 1 FROM conflict_folder_divergent_move_note_chains c WHERE c.operation_id=n.operation_id AND c.note_id=n.note_id AND c.old_operation_id=o.operation_id)) AND d.state IN ('evacuated','canonical_published','completed')) AND NOT EXISTS(SELECT 1 FROM sync_folder_preserve_delete_clones c JOIN sync_folder_preserve_delete_resolutions p ON p.conflict_operation_id=c.conflict_operation_id WHERE c.original_folder_id=o.object_id AND p.state='resolved'))
 OR (o.status='conflict' AND NOT EXISTS(SELECT 1 FROM sync_conflict_resolutions r WHERE r.operation_id=o.operation_id) AND NOT EXISTS(SELECT 1 FROM conflict_materializations m WHERE m.operation_id=o.operation_id AND m.state IN ('copy_staged','copy_published','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_create_recoveries f WHERE f.operation_id=o.operation_id AND f.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_move_delete_recoveries d WHERE d.operation_id=o.operation_id AND d.state IN ('moved','completed')) AND NOT EXISTS(SELECT 1 FROM conflict_folder_divergent_move_recoveries d WHERE d.operation_id=o.operation_id AND d.state IN ('evacuated','canonical_published','completed')) AND NOT EXISTS(SELECT 1 FROM sync_folder_preserve_delete_resolutions p WHERE p.conflict_operation_id=o.operation_id AND p.state='resolved'));
